# Generated by Django 6.0.6 on 2026-06-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('nota', models.IntegerField(default=0)),
                ('assistido', models.BooleanField(default=False)),
            ],
        ),
    ]
